name: Build GTA SA AML Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Verify NDK
        run: $ANDROID_NDK_ROOT/ndk-build --version

      - name: Build
        run: |
          $ANDROID_NDK_ROOT/ndk-build \
            NDK_PROJECT_PATH=. \
            APP_BUILD_SCRIPT=Android.mk \
            NDK_APPLICATION_MK=Application.mk \
            NDK_DEBUG=0

      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: AML-Mod
          path: libs/**/*.so
